#%RAML 1.0
title: MEMBER-SYSTEM-API
description: This RAML file describes structure of all member system API.

traits:
  client-id-enforcement: !include /exchange_modules/98e79d99-3e6a-4d80-889b-76dc9755b161/fragment-common-traits/1.0.2/client-id-enforcement-header-trait.raml
  common-trait: !include /exchange_modules/98e79d99-3e6a-4d80-889b-76dc9755b161/fragment-common-traits/1.0.2/common-header-trait.raml
  member-queryParams: !include /exchange_modules/98e79d99-3e6a-4d80-889b-76dc9755b161/fragment-common-traits/1.0.2/member-queryParams-traits.raml

types:
  member-details-datatypes: !include /exchange_modules/98e79d99-3e6a-4d80-889b-76dc9755b161/fargment-datatypes/1.0.1/Members/member-details-dataType.raml 
  post-member-details-response: !include /exchange_modules/98e79d99-3e6a-4d80-889b-76dc9755b161/fargment-datatypes/1.0.1/Members/post-member-details-response-dataType.raml 
  error-response-datatype: !include /exchange_modules/98e79d99-3e6a-4d80-889b-76dc9755b161/fargment-datatypes/1.0.1/Errors/error-response-dataType.raml
  member-patch-details: !include /exchange_modules/98e79d99-3e6a-4d80-889b-76dc9755b161/fargment-datatypes/1.0.1/Members/member-patch-details-dataType.raml

/members:
  /{memberId}:
    patch:
      description: This API will update member details.
      is: [client-id-enforcement , common-trait]
      body:
        application/json:
          description: This is success response for get member detaild api
          type: member-patch-details
          example: !include /Examples/member-details.json
      responses:
        200:
          body:
            application/json:
              type: post-member-details-response
              example: !include /Examples/200-sucess-response.json                        
        400:
          body:
            application/json:
              type: error-response-datatype
              example: !include /Examples/error-400-response-example.json
              
        401:
          body:
            application/json:
              type: error-response-datatype
              example: !include /Examples/error-401-response-example.json
        404:
            body:
              application/json:
                type: error-response-datatype
                example: !include /Examples/error-404-response-example.json
        500:
          body:
              application/json:
                type: error-response-datatype
                example: !include /Examples/error-500-response-example.json  
    get:
      description: This API will fetch member details.
      is: [client-id-enforcement , common-trait]
      responses:
        200:
          body:
            application/json:
              description: This is success response for get member detaild api
              type: member-details-datatypes
              example: !include /Examples/member-details.json          
        400:
          body:
            application/json:
              type: error-response-datatype
              example: !include /Examples/error-400-response-example.json
        401:
          body:
            application/json:
              type: error-response-datatype
              example: !include /Examples/error-401-response-example.json
        404:
          body:
            application/json:
              type: error-response-datatype
              example: !include /Examples/error-404-response-example.json
        500:
          body:
            application/json:
              type: error-response-datatype
              example: !include /Examples/error-500-response-example.json              
  post:
    description: This API will post member details.
    is: [client-id-enforcement , common-trait]
    body:
      application/json:
        description: This is success response for get member detaild api
        type: member-details-datatypes
        example: !include /Examples/member-details.json
    responses:
      200:
        body:
          application/json:
            type: post-member-details-response
            example: !include /Examples/200-sucess-response.json                        
      400:
        body:
          application/json:
            type: error-response-datatype
            example: !include /Examples/error-400-response-example.json
             
      401:
        body:
          application/json:
            type: error-response-datatype
            example: !include /Examples/error-401-response-example.json
      404:
          body:
            application/json:
              type: error-response-datatype
              example: !include /Examples/error-404-response-example.json
      500:
        body:
            application/json:
              type: error-response-datatype
              example: !include /Examples/error-500-response-example.json
  get:
    description: This API will fetch member details.
    is:
      - client-id-enforcement 
      - common-trait
      - member-queryParams
    responses:
      200:
        body:
          application/json:
            description: This is success response for get member detaild api
            type: object
            properties:
              memberList:
                type: array
                items:
                  type: member-details-datatypes             
                  example: !include /Examples/member-details.json          
      400:
        body:
          application/json:
            type: error-response-datatype
            example: !include /Examples/error-400-response-example.json
      401:
        body:
          application/json:
            type: error-response-datatype
            example: !include /Examples/error-401-response-example.json
      404:
        body:
          application/json:
            type: error-response-datatype
            example: !include /Examples/error-404-response-example.json
      500:
        body:
          application/json:
            type: error-response-datatype
            example: !include /Examples/error-500-response-example.json  
  /sync:
    post:
      description: This API will post member details.
      is: [client-id-enforcement , common-trait]
      body:
        application/json:
          description: This is success response for get member detaild api
          type: member-details-datatypes
          example: !include /Examples/member-details.json
      responses:
        200:
          body:
            application/json:
              type: post-member-details-response
              example: !include /Examples/200-sucess-response.json                        
        400:
          body:
            application/json:
              type: error-response-datatype
              example: !include /Examples/error-400-response-example.json
              
        401:
          body:
            application/json:
              type: error-response-datatype
              example: !include /Examples/error-401-response-example.json
        404:
            body:
              application/json:
                type: error-response-datatype
                example: !include /Examples/error-404-response-example.json
        500:
          body:
              application/json:
                type: error-response-datatype
                example: !include /Examples/error-500-response-example.json
    

        
